### ISSUE TITLE
Error when checking color of the badge

### ISSUE THREAD

**Issue by fabios15** [tmxkn1/Microsoft-Reward-Chrome-Ext#10]
Hi, when I click the _Check now_ button I get some error messages in the Chrome extension panel and the extension'icon is red ![error](https://user-images.githubusercontent.com/33929590/126752883-9dd90622-b091-4ea6-b2b8-d1aeeba49424.png).
In particular, it shows two errors:

1. Access to fetch at 'https://rewards.microsoft.com/pointsbreakdown?redref=amc' (redirected from 'https://account.microsoft.com/rewards/pointsbreakdown') from origin 'chrome-extension://ddoaniekjjahkgafekbedojaehjndnkd' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
2. Uncaught (in promise) FetchFailed: Fetch failed because an exception occurred.

    **Stack analysis** error at line status/DailyRewardStatus.js:83
     https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/70c3925c7131541bdf6e5dd08b5133fa99f1e264/src/status/DailyRewardStatus.js#L83

**Comment by filipverlee** [comment]
Context

_generated_background_page.html
Stack Trace
status/DailyRewardStatus.js:138 (Anonymous function)

   }
        try {
            this._parseStatusJson(statusJson);
        } catch (ex) {
            if (ex.name == 'TypeError' || ex.name == 'ReferenceError') {
                throw new ParseJSONFailedException('Status', ex);
            }
        }
    }

**Comment by tmxkn1** [comment]
This has been solved.
