### ISSUE TITLE
Mobile searches Stopped working.

### ISSUE THREAD

**Issue by OcciZio** [tmxkn1/Microsoft-Reward-Chrome-Ext#101]
it currently stopped doing the mobile searches. possibly just a bug but if not any info on how i can fix it would be appreciated. 
![Screenshot_1](https://user-images.githubusercontent.com/103053757/227215150-aa30e54a-77fa-41d9-bf9f-7d0b794cde17.png)
> I tried providing the Debug info but it was too long. If need just lmk.

**Comment by LittleBigMan81** [comment]
I think it was an issue with MS Rewards, I couldn't even get into the site earlier.  It's working now for me tho....

**Comment by OcciZio** [comment]
Yeah it seems to be all fixed
