### ISSUE TITLE
Check now button not visible

### ISSUE THREAD

**Issue by YASH-PRAKASH** [tmxkn1/Microsoft-Reward-Chrome-Ext#106]
![image](https://user-images.githubusercontent.com/60319483/229354928-6e2d37bc-c2bb-4edd-8615-3c2b4215d7fc.png)
i cannot find the check now button to refresh it even after installing the extension multiple times and updating it to the latest version.

rest everything is working fine, also why does it not seem to work when i use a vpn? do we not have a solution for that?

**Comment by tmxkn1** [comment]
It is a legacy feature. I have updated the related content in the readme file. Sorry for the confusion.

The new way of doing this is by simply clicking the badge button.

**Comment by tmxkn1** [comment]
Regarding the VPN issue, which country are you in and what is the redirected/final URL looks like when you visit [Microsoft Reward](https://rewards.bing.com/?signin=1)?

**Comment by YASH-PRAKASH** [comment]
it's all sorted now, though the mobile searches don't work automatically anymore, u have to use ABS and mobile switcher now to do the mobile searches, this does not do it by itself! else everything is great now, btw do you have any idea what to do if ur account is suspended?

**Comment by tmxkn1** [comment]
> it's all sorted now, though the mobile searches don't work automatically anymore, u have to use ABS and mobile switcher now to do the mobile searches, this does not do it by itself! else everything is great now, btw do you have any idea what to do if ur account is suspended?

This is probably due to an UA issue. I have updated the hosted UA, the extension should work normally now.
