### ISSUE TITLE
It keeps showing "err"

### ISSUE THREAD

**Issue by userNOTcoder** [tmxkn1/Microsoft-Reward-Chrome-Ext#110]
It keeps showing that its not working even though i am logged in my microsoft account

**Comment by LittleKnightG** [comment]
i have been having the same issue, i do not see the check now button

**Comment by suckurmom** [comment]
Having the same issues, it doesnt automatically do the desktop, mobile and browser searchers

**Comment by matbtn** [comment]
Same here, with the latest version Microsoft-Reward-Chrome-Ext-2.24.2.1

**Comment by tmxkn1** [comment]
Hi if you are still having this issue, please open a new ticket and report it with more details. Thank you :)
