### ISSUE TITLE
BROKEN BUTTON

### ISSUE THREAD

**Issue by RRRandom-Youtube** [tmxkn1/Microsoft-Reward-Chrome-Ext#111]
Fix Button When I Click On It doesn't work click task

**Comment by tmxkn1** [comment]
Hi, thank you for reporting the issue. I struggle to understand you. Can you please rephrase your sentence?

**Comment by ninjatall12** [comment]
I think he meant that clicking on the activities the daily set or more activities does not open a hyperlink to the activity. the stuff that's supposed to be here 
![image](https://user-images.githubusercontent.com/58861295/232311747-9ed87b27-69c6-4b0e-986f-6891ed1660ce.png)

**Comment by RRRandom-Youtube** [comment]
> Hi, thank you for reporting the issue. I struggle to understand you. Can you please rephrase your sentence?

![image](https://user-images.githubusercontent.com/88394176/232319814-a132937e-79e9-4773-8633-44889e7eadca.png)

**Comment by xxEndGamingxx** [comment]
I think with this [RRRandom-Youtube] is saying is that the buttons do not work I also have a video that I'm going to submit

https://user-images.githubusercontent.com/84996590/232351656-bad56fba-b292-4f52-ad69-72ed97b7f0a9.mp4

**Comment by tmxkn1** [comment]
Please see my reply in https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/115#issuecomment-1523941172 for details
