### ISSUE TITLE
RED colour error 

### ISSUE THREAD

**Issue by Skewter** [tmxkn1/Microsoft-Reward-Chrome-Ext#112]
I am signed into my microsoft account. But still it shows error of red colour. This error is is not constant though. Extension would work some times, sometimes won't work. Extension works some time of the day but shows error other times. 

     Is the extension offline some time of the day? Like, it works some times then it won't work again randomly. 
![image](https://user-images.githubusercontent.com/107710807/232286432-b44209aa-b2b3-45e0-97ac-b6dc9b05a0c6.png)
![image](https://user-images.githubusercontent.com/107710807/232286696-a908d635-0468-4587-a78a-9f0a8f9b1f94.png)

**Comment by esfomeado** [comment]
Having the same issue.

**Comment by LittleBigMan81** [comment]
Having the same issue, usually with Mobile searches, and has been happening for about 4 to 6 weeks now.

**Comment by Th2ophile2M** [comment]
I fix the issue with the new option "Mobile user agent override".
It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/)indicates.
I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again.
Sorry for my bad English

**Comment by tmxkn1** [comment]
> I am signed into my microsoft account. But still it shows error of red colour. This error is is not constant though. Extension would work some times, sometimes won't work. Extension works some time of the day but shows error other times.
> 
> ```
>  Is the extension offline some time of the day? Like, it works some times then it won't work again randomly. 
> ```
> 
> ![image](https://user-images.githubusercontent.com/107710807/232286432-b44209aa-b2b3-45e0-97ac-b6dc9b05a0c6.png) ![image](https://user-images.githubusercontent.com/107710807/232286696-a908d635-0468-4587-a78a-9f0a8f9b1f94.png)

The issue with this is probably due to some network error on your end that the extension is not able to download UA from Github. It may be temporary.

**Comment by tmxkn1** [comment]
> I fix the issue with the new option "Mobile user agent override". It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/)indicates. I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again. Sorry for my bad English

I would advice against using a bingbot useragent. It may get you banned.

**Comment by Aryytt** [comment]
@tmxkn1 I have used this method today. Will I get banned for using this now? I'm really worried.

> > I fix the issue with the new option "Mobile user agent override". It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/)indicates. I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again. Sorry for my bad English
> 
> I would advice against using a bingbot useragent. It may get you banned. I have updated the hosted UA so override should not be necessary.

**Comment by tmxkn1** [comment]
> @tmxkn1 I have used this method today. Will I get banned for using this now? I'm really worried.
> 
> > > I fix the issue with the new option "Mobile user agent override". It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/)indicates. I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again. Sorry for my bad English
> > 
> > 
> > I would advice against using a bingbot useragent. It may get you banned. I have updated the hosted UA so override should not be necessary.

Don't worry about it too much. I don't think using it once or twice will cause any issue, but don't use it days after days.

**Comment by Aryytt** [comment]
Alright, thank you!
