### ISSUE TITLE
No Mobile  Searches

### ISSUE THREAD

**Issue by LittleBigMan81** [tmxkn1/Microsoft-Reward-Chrome-Ext#113]
Tried multiple accounts and the extension is not making any mobile searches.  Using an updated Edge browser.

One time I got a Red "Err" message, but as soon as I clicked it the Extension bade turned to its normal color.

I did five accounts and I was able to successfully do all activities and daily searches except for Mobile.

**Comment by Nujra40** [comment]
I have the same issue too

**Comment by Th2ophile2M** [comment]
I fix the issue with the new option "Mobile user agent override".
It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/) indicates.
I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again.
Sorry for my bad English

**Comment by tmxkn1** [comment]
> I fix the issue with the new option "Mobile user agent override". It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/) indicates. I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again. Sorry for my bad English

As I mentioned in the other issue, it is best to avoid bingbot UA. It may get flagged easily. I have updated the hosted UA so this issue should be gone now without need of the UA override.

**Comment by Th2ophile2M** [comment]
> > I fix the issue with the new option "Mobile user agent override". It seems to me that the user agent is changing, as this [site ](https://www.searchenginejournal.com/new-bingbot-user-agent/448023/) indicates. I use this UA: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/W.X.Y.Z Mobile Safari/537.36 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm) and it's working again. Sorry for my bad English
> 
> As I mentioned in the other issue, it is best to avoid bingbot UA. It may get flagged easily. I have updated the hosted UA so this issue should be gone now without need of the UA override.

Ok I understand thanks a lot
