### ISSUE TITLE
Invalid user agents (on alter accounts)

### ISSUE THREAD

**Issue by VasuBhimani** [tmxkn1/Microsoft-Reward-Chrome-Ext#119]
**Affected user agents**
PC and/or mobile

**Since when**
3 days ago

**Comments**

i tried so many user agent to solve this issue. i have multiple chromes icons with multiple chrome ID's so in my some id this extension work properly but in my some other chrome account shows user agent invalid error like this 

![Screenshot 2023-04-28 161253](https://user-images.githubusercontent.com/112377821/235128972-e3bc4c4d-77e1-4e79-afd7-f8a93e3241b1.png)

in my this ID it work properly :-

![Screenshot (22)](https://user-images.githubusercontent.com/112377821/235127725-a89a7cd3-7b77-46d2-a3c8-8b21addb0104.png)

in my this id it show error :-

![Screenshot (25)](https://user-images.githubusercontent.com/112377821/235128086-726546ff-c595-4888-a297-1327b353aa49.png)

same kind of erroe with different kind of description :-

![Screenshot (26)](https://user-images.githubusercontent.com/112377821/235128338-b53ac306-2778-4edc-8efc-c26e16afad5f.png)

and also some accounts automatically starts working and after some time or day it will automatically stops working again

**Comment by tmxkn1** [comment]
Have you checked the extension options in each of your accounts? In your third example, user agent overrides are enabled but you probably have left the input boxes empty.

**Comment by tmxkn1** [comment]
Also, what are the user agents in the account that work?

**Comment by VasuBhimani** [comment]
> Have you checked the extension options in each of your accounts? In your third example, user agent overrides are enabled but you probably have left the input boxes empty.

yaa i just check this mistake in third account and you are right but can you please tell me solution for my second example

**Comment by VasuBhimani** [comment]
> Also, what are the user agents in the account that work?

i tried my user agent for this but nothing is work, in my first example i do nothing special this is working without any user agent but some other account shows user agent error like i shows you in second example

**Comment by Speil** [comment]
Got this too
![image](https://user-images.githubusercontent.com/16503921/235185128-76b2d2d6-d516-4b6e-b194-e3e74f0107dd.png)

Here's my error log: https://pastebin.com/X3g1Nnzw

**Comment by VasuBhimani** [comment]
i tried 10 to 15 different user agent but nothing is work

![Screenshot (28)](https://user-images.githubusercontent.com/112377821/235307019-3c040e0b-16ff-415a-ad54-446fff8d4e3b.png)

in my other account this is working properly ( without adding additional user agent i just load extention on chrome and it starts working )

![Screenshot (29)](https://user-images.githubusercontent.com/112377821/235307128-a0fc74be-1f7f-409d-873d-198f6984ce75.png)

**Comment by tmxkn1** [comment]
I'm not sure why. Are you able to do manual searches on those accounts?

**Comment by VasuBhimani** [comment]
yes, manual search work perfectly

**Comment by tmxkn1** [comment]
> yes, manual search work perfectly

The reasons I can think of are:

1. Your alter accounts are not logged into https://www.bing.com/ or/and https://rewards.bing.com/
2. Your alter accounts are banned.

But since you confirmed manual search works, I don't know what else can be the reason.

Things to try regardless:

1. Remove the extension and reinstall it.
2. Use your browser's native UA to see if that works (mimicking a manual search). Visit: https://www.whatsmyua.info/ and copy and paste the UA in the override box.
3. Try the [latest develop version](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/archive/refs/heads/master.zip). I updated the request header, not well tested, so it may be complete garbage...

**Comment by VasuBhimani** [comment]
thank you for your reply and i tried all 3 things but nothing is work :(

i want to addon something, that i use different bot for bing search before this but after some days ( 4-5 day ) they all bots are stop working or not perform mobile search or they take so many time to complete search and this same happen with this extension also in staring 3-4 days this is work properly but after that some account giving UA error and some account still working properly. i don't know this will help or not but just telling you if this can help you to solve my problem

**Comment by VasuBhimani** [comment]
> > yes, manual search work perfectly
> 
> The reasons I can think of are:
> 
> 1. Your alter accounts are not logged into https://www.bing.com/ or/and https://rewards.bing.com/
>    
>    * You must log into both sites.
>    * Make sure you click the badge on [www.bing.com](http://www.bing.com) to double check it.
> 2. Your alter accounts are banned.
> 
> But since you confirmed manual search works, I don't know what else can be the reason.
> 
> Things to try regardless:
> 
> 1. Remove the extension and reinstall it.
> 2. Use your browser's native UA to see if that works (mimicking a manual search). Visit: https://www.whatsmyua.info/ and copy and paste the UA in the override box.
> 3. Try the [latest develop version](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/archive/refs/heads/master.zip). I updated the request header, not well tested, so it may be complete garbage...

thank you for your reply and i tried all 3 things but nothing is work :(

i want to addon something, that i use different bot for bing search before this but after some days ( 4-5 day ) they all bots are stop working or not perform mobile search or they take so many time to complete search and this same happen with this extension also in staring 3-4 days this is work properly but after that some account giving UA error and some account still working properly. i don't know this will help or not but just telling you if this can help you to solve my problem

**Comment by tkon99** [comment]
Hi all, just wanted to share an observation, it seems that they are filtering search terms. Single/two word terms are ignored in the points but entering a longer query counts points for me. Perhaps this is the time to use AI generated search queries? :)

**Comment by ElDavoo** [comment]
I tried concatening three queries like this:
```js
    _getBingSearchUrl() {
        const word = this._currentSearchType_ == SEARCH_TYPE_PC_SEARCH ?
            this._googleTrend_.nextPCWord + " " + this._googleTrend_.nextPCWord + " " + this._googleTrend_.nextPCWord :
            this._googleTrend_.nextMBWord + " " + this._googleTrend_.nextMBWord + " " + this._googleTrend_.nextMBWord ;

        return `https://www.bing.com/search?q=${word}`;
    }
```
but nothing changed

**Comment by Speil** [comment]
I installed the addon on firefox and its working as expected. So I can rule out problems with my account or the search terms of the addon

**Comment by Speil** [comment]
> Got this too ![image](https://user-images.githubusercontent.com/16503921/235185128-76b2d2d6-d516-4b6e-b194-e3e74f0107dd.png)
> 
> Here's my error log: https://pastebin.com/X3g1Nnzw

out of a sudden my chrome extension is working fine again - without any changes from my side

**Comment by VasuBhimani** [comment]
i have one update on my this issue that this extension working for me only few days per browser. i run this extension on chrome  where it is perfeclty work for 5-6 days after that it gives UA erroes after that i tried on microsoft edge and  also here after 5-6 days it gives UA errors and at last i tries Brave and same problem i face here after 5 days

anyone know why it's happen with me ??
