### ISSUE TITLE
Error - CORS Policy

### ISSUE THREAD

**Issue by azz22** [tmxkn1/Microsoft-Reward-Chrome-Ext#12]
Error with new rewards page on MS rewards. The error is saying its soemthings to do with the CORS policy.
<img width="627" alt="Screenshot 2021-08-14 at 22 46 23" src="https://user-images.githubusercontent.com/19947349/129460869-cfa7f40a-b540-4a16-85df-ed834a57def7.png">

Thanks

**Comment by tmxkn1** [comment]
Can you show the full error message please?

**Comment by azz22** [comment]
Hi, I dont know how to get the errors in a log format but i have a screenshot if that helps. Let me know if not.
<img width="965" alt="Screenshot 2021-08-15 at 11 06 29" src="https://user-images.githubusercontent.com/19947349/129474866-0bed3368-c1c3-421a-a98b-f56a5b04c56d.png">

**Comment by tmxkn1** [comment]
Hi, sorry it doesn't really help with debugging (my bad exception handling). But it looks like an unknown error occurred when attempting to fetch using the correct URL. 

I have updated the code with better exception handling, which should help me diagnose this issue. Could you update to the latest, reload the extension, then wait 5 seconds. The extension should start to do work on its own. Once it shows an error icon, send me the screenshot of the console, make sure to include all the messages.

**Comment by azz22** [comment]
Morning, Ive copied and pasted the errors into a .txt file. Its actually started working today. nothings changed. Really appreciate your help though. Thanks.

Cheeky request - Would there be a way where the bot could complete the daily set or activities. Most are just clicking, I appreciate the surveys/quiz's are probably not do-able. This would just complete the automation and allow for more points with even less effort ;) Thanks.
 
[MS Reward Bot Errors.txt](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/files/6991530/MS.Reward.Bot.Errors.txt)

**Comment by tmxkn1** [comment]
> Morning, Ive copied and pasted the errors into a .txt file. Its actually started working today. nothings changed. Really appreciate your help though. Thanks.

No problem. Glad it "sorts" itself out.

> Cheeky request - Would there be a way where the bot could complete the daily set or activities. Most are just clicking, I appreciate the surveys/quiz's are probably not do-able. This would just complete the automation and allow for more points with even less effort ;) Thanks.

I'm not sure if it is possible for a background extension as with `fetch` I can only get the basic HTML - the contents generated by embedded javascript are missing. Those links are unfortunately dynamically generated and protected by hashes. I attempted to extract the hashes from the user_status json, but those hashes do not work for some reason. I suppose I need to dig further, but for now, I am using [Microsoft-Rewards-Bot](https://github.com/tmxkn1/Microsoft-Rewards-Bot)

**Comment by azz22** [comment]
Thanks for the link. I’ll have a look at that. Again, I appreciate your help.
