### ISSUE TITLE
New Extension Update Searches Not Working (only does 1-2 searches before error)

### ISSUE THREAD

**Issue by GreenSussy** [tmxkn1/Microsoft-Reward-Chrome-Ext#120]
**I have read the Troubleshooting**
Yes

**Describe the bug**
I recently saw the new update that rolled out for the extension. I updated it, and it worked fine for about 3-4 days. Now, it gives me a red err. When I click on it, it turns blue but nothing happens. For some reason, it gives me only 6 Edge searches per day. 

**Since when**
Since 2 days ago.

**Screenshots**
![image](https://user-images.githubusercontent.com/114675511/235308921-ce7c0b5b-3352-4b81-b89c-1d67b9206fe3.png)
This is all I can find in the chrome://extensions. Let me know if you need anything else.

**Your country**
I am residing in the United States.

**Your web browser and OS**
Chrome Version 112.0.5615.138 (Official Build) (64-bit)
Windows 11 Home 22H2

**Additional context**
I wonder what the issue is. Also, just a side note - it still says "Extension Update Available" even after updating it to the latest release. I don't know if this is directly or indirectly related but I just wanted to point it out. Thanks!

**Comment by ElDavoo** [comment]
I also have this problem, but is locked out at 3, not 6.

**Comment by VasuBhimani** [comment]
i am also facing same issue and i tried different user agent to resolve this but nothing is work and some time it locked on 3 and some time it does not give a single search point

**Comment by LeFlairGoD** [comment]
Same problem here:
If you need more information just Ask.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/64659197/235340827-668e94d9-1589-43b1-8f8f-06ea12aafc1a.png">

**Comment by tmxkn1** [comment]
I'm unsure if this is MS's attempt to counter the script. If the user agent works once, it should work all the way.

> it still says "Extension Update Available" even after updating it to the latest release

Have you installed the [hotfix](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/releases/tag/v2.24.2.1)?

**Comment by GreenSussy** [comment]
@tmxkn1 Oh I didn't see the updated ZIP file. Now that message is gone.
Seems that the main issue is still there. Please do keep us updated on any new fixes/findings you have. Thanks!

**Comment by PlsFixTheErrorMan** [comment]
![image](https://user-images.githubusercontent.com/131081256/235379839-f17fd322-f6b8-4ebf-a56c-823613931ae4.png)

**Comment by Aseese** [comment]
I had the same issue but I fixed it. I just cleared my web browser cache completely. After logging back into microsoft rewards it began functioning again as intended. Just clear your web browser cache.

**Comment by GreenSussy** [comment]
I noticed today that it is locked at 3 searches for ME. Wonder why.

**Comment by PlsFixTheErrorMan** [comment]
heres my error
![image](https://user-images.githubusercontent.com/131081256/235566604-176b1e3f-3a8d-4d39-adca-98a3b9649fe4.png)

**Comment by LeFlairGoD** [comment]
> I had the same issue but I fixed it. I just cleared my web browser cache completely. After logging back into microsoft rewards it began functioning again as intended. Just clear your web browser cache.

Thank you, this has helped me.
![image](https://user-images.githubusercontent.com/64659197/235585802-2626a00a-fb6d-4c65-b596-0df81d2cd21b.png)

**Comment by ivelweyz** [comment]
> I'm unsure if this is MS's attempt to counter the script. If the user agent works once, it should work all the way.
> 
They might have. Last tuesday/wednesday they started cracking down on the VPN/multi country trick, and some others, and that's the last day this script has worked for me. It no longer functions, at all.

**Comment by warmfire540** [comment]
> > I had the same issue but I fixed it. I just cleared my web browser cache completely. After logging back into microsoft rewards it began functioning again as intended. Just clear your web browser cache.
> 
> Thank you, this has helped me. ![image](https://user-images.githubusercontent.com/64659197/235585923-45097737-3807-4c1f-8b29-4e4eb5e728bb.png)

What version are you running?

**Comment by LeFlairGoD** [comment]
> > > Ich hatte das gleiche Problem, aber ich habe es behoben. Ich habe gerade den Cache meines Webbrowsers komplett geleert. Nachdem ich mich wieder bei Microsoft Rewards angemeldet hatte, funktionierte es wieder wie vorgesehen. Löschen Sie einfach den Cache Ihres Webbrowsers.
> > 
> > 
> > Danke, das hat mir geholfen.![Bild](https://user-images.githubusercontent.com/64659197/235585923-45097737-3807-4c1f-8b29-4e4eb5e728bb.png)
> 
> Welche Version hast du?

![image](https://user-images.githubusercontent.com/64659197/235735636-1d97e142-82f8-4356-ab4b-fe756a6cfa00.png)

**Comment by Emanuads** [comment]
> I had the same issue but I fixed it. I just cleared my web browser cache completely. After logging back into microsoft rewards it began functioning again as intended. Just clear your web browser cache.

Worked for me too! Thanks!

**Comment by GreenSussy** [comment]
Just tried clearing the cookies and cache. Doesn't seem to change anything on my end; I'll let it sit for a night and see what happens tomorrow.

**Comment by PlsFixTheErrorMan** [comment]
is this how i clear my cache?

**Comment by PlsFixTheErrorMan** [comment]
![image](https://user-images.githubusercontent.com/131081256/235820431-66297c93-c08a-4d01-a9f5-29500dc1f87e.png)

**Comment by RoyEastmen** [comment]
> > > > Ich hatte das gleiche Problem, aber ich habe es behoben. Ich habe gerade den Cache meines Webbrowsers komplett geleert. Nachdem ich mich wieder bei Microsoft Rewards angemeldet hatte, funktionierte es wieder wie vorgesehen. Löschen Sie einfach den Cache Ihres Webbrowsers.
> > > 
> > > 
> > > Danke, das hat mir geholfen.![Bild](https://user-images.githubusercontent.com/64659197/235585923-45097737-3807-4c1f-8b29-4e4eb5e728bb.png)
> > 
> > 
> > Welche Version hast du?
> 
> ![image](https://user-images.githubusercontent.com/64659197/235735636-1d97e142-82f8-4356-ab4b-fe756a6cfa00.png)

That worked, thanks!

**Comment by GreenSussy** [comment]
Clearing the cache didn't help me. RIP

**Comment by GreenSussy** [comment]
![image](https://user-images.githubusercontent.com/114675511/236030317-9fc85824-727c-4bde-9f80-54ce412d0261.png)

**Comment by GreenSussy** [comment]
@tmxkn1 sorry for being annoying, but do you have any new updates on this issue?

**Comment by LeFlairGoD** [comment]
> @tmxkn1 sorry for being annoying, but do you have any new updates on this issue?

Install the latest Chrome update (version 113.0.5672.63), empty the cache completely (note that you usually only empty the current day) and install the latest version of the add-on (2.24.2.1) :

![image](https://user-images.githubusercontent.com/64659197/236380563-5f1a1798-590e-43c7-9f3f-35bb9dfe9f6c.png)

**Comment by tmxkn1** [comment]
Sorry I am currently on vacation so will have very limited access to internet and have no means to run any test.

On 5 May 2023, at 13:00, LeFlairGoD ***@***.***> wrote:



@tmxkn1<https://github.com/tmxkn1> sorry for being annoying, but do you have any new updates on this issue?

Install the latest Chrome update (version 113.0.5672.63), empty the cache completely (note that you usually only empty the current day) and install the latest version of the add-on (2.24.2.1) :

[image]<https://user-images.githubusercontent.com/64659197/236380563-5f1a1798-590e-43c7-9f3f-35bb9dfe9f6c.png>

**Comment by LeFlairGoD** [comment]
Interesting, I have 2 accounts, one of them collected automatically today, the other one I had to clear the cache first so that it collects.

**Comment by GreenSussy** [comment]
@tmxkn1 Miraculously, it is working perfectly now. Just curious - did you make any changes on your side?

**Comment by LeeRyanSA** [comment]
It magically started to work once again. 
hm

**Comment by tmxkn1** [comment]
> @tmxkn1 Miraculously, it is working perfectly now. Just curious - did you make any changes on your side?

I did not. It could be some weird issue on MS's end which is not uncommon.
