### ISSUE TITLE
It shows manifest version 2 is deprecated 

### ISSUE THREAD

**Issue by kevaleaditya81** [tmxkn1/Microsoft-Reward-Chrome-Ext#121]
Help me out......
![ms err](https://user-images.githubusercontent.com/101872439/236382749-62e6bf7a-d2a3-4645-be28-07d5f5a5c6ea.png)

**Comment by LeFlairGoD** [comment]
> Help me out...... ![ms err](https://user-images.githubusercontent.com/101872439/236382749-62e6bf7a-d2a3-4645-be28-07d5f5a5c6ea.png)

You should first read over the other problems, then you would have seen that this is not a new one
https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/37
