### ISSUE TITLE
Manifest Isnt working please fix it

### ISSUE THREAD

**Issue by LEONJUSTIN** [tmxkn1/Microsoft-Reward-Chrome-Ext#122]
- Do not report invalid user agents.
- Make sure you have read the troubleshooting before submitting a bug report.

----
**I have read the Troubleshooting**
Yes/No

**Describe the bug**

**Since when**
e.g. a day ago.

**Screenshots**
Add screenshots of the error page if possible.

**Your country**
Each country may have a unique MS reward data scheme. Therefore, it may be useful to know your country of residence. You may choose not to provide.

**Your web browser and OS**
e.g. Chrome Windows, Safari MacOS, etc.

**Additional context**

**Comment by tmxkn1** [comment]
See #37
