### ISSUE TITLE
Manifest Version 2 has expired and causing errors. 

### ISSUE THREAD

**Issue by AryanPlaysChess** [tmxkn1/Microsoft-Reward-Chrome-Ext#123]
**Hello**, I'm Aryan and have been facing this issue from your software. I hope to seek help on how to fix this error. 
![image](https://user-images.githubusercontent.com/74579820/236635628-4d6f15b8-ef60-4e5a-b94f-adfe5b7cbce2.png)

I needed this extension as I wanted to get some rewards for doing nothing. **I hope you can fix my error.**

My PC Details, (If that helps.)

Browser: Microsoft Edge Version 112.0.1722.68
PC: Acer Aspire 3 (E5-573)

**Comment by tmxkn1** [comment]
I don't think it is manifest v2 causing the error, but if you want to try manifest v3, you can download it [here](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/archive/refs/heads/manifest-3.zip)

**Comment by tmxkn1** [comment]
The issue you have is probably already raised here in #118
