### ISSUE TITLE
Showing error with the red tag and unable to do searches

### ISSUE THREAD

**Issue by gianniskapta** [tmxkn1/Microsoft-Reward-Chrome-Ext#124]
**I have read the Troubleshooting**
Yes

**Describe the bug**
The extension has been showing the red error message and update notice, even after uninstalling and installing it back. I've updated it but it keeps showing me 'update available.' Still unable to do any searches. Please what can i do here?

**Since when**
2days ago

**Screenshots**
![image](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/70020264/080df5c6-47e1-4329-8adc-788a018ea9ab)

**Your country**
US

**Your web browser and OS**
Chrome Windows, even after changing it to another user agent, i still got same error.

**Additional context**
Here are the errors
![image](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/70020264/2ce58c75-708d-4658-a872-7b2ac3c1afe7)
.

**Comment by tmxkn1** [comment]
The latest version is here: https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/releases/tag/v2.24.2
