### ISSUE TITLE
[ParseJSONFailed: Fail to parse the received json document.] Not doing searches.

### ISSUE THREAD

**Issue by manoj150816** [tmxkn1/Microsoft-Reward-Chrome-Ext#125]
**I have read the Troubleshooting**
Yes

**Describe the bug**
Not doing searches and the extension turns red after like 1 min and this error pops up( Refer to screenshot below)

**Since when**
A day ago.

**Screenshots**
![image](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/116278198/06ff529a-6a3d-4444-b7c5-7700a02bb5b7)

**Your country**
India

**Your web browser and OS**
Chrome Windows

**Additional context**
Fix this ASAP

**Comment by improbir** [comment]
yea same issue please fix this problem

**Comment by tmxkn1** [comment]
It is a user agent issue which may resolve by itself the next day or the day after.
