### ISSUE TITLE
Extension stuck on a microsoft announcement

### ISSUE THREAD

**Issue by MDanyalT** [tmxkn1/Microsoft-Reward-Chrome-Ext#129]
I have read the Troubleshooting:
yes

Describe the bug A clear and concise description of what the bug is.
extension shows an err sign, when clicked it shows a Microsoft announcement saying "Earn free gift cards and more with Microsoft Rewards". Has the option to "Join and redeem" but when clicked in it doesn't do anything

Since when e.g. a day ago.
Today, after I signed in with another Microsoft account that also had been used for Microsoft rewards, but problem still persists even after signing out of that said acccount.

Screenshots If applicable, visit chrome://extensions page and click the Errors next to this extension. Take screenshots of the errors and add them here.
<img width="319" alt="Screenshot 2023-06-24 at 12 54 42 AM" src="https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/130467407/798f7e61-a688-47a5-9274-6f583f38204a">

Your country Each country may have a unique MS reward data scheme. Therefore, it may be useful to know your country of residence.
UK

Your web browser and OS e.g. Chrome Windows, Safari MacOS, etc.
Chrome MacOS

**Comment by whosal1ce** [comment]
having the same problem

**Comment by MDanyalT** [comment]
yes youre right, it worked. Thank you
