### ISSUE TITLE
Not doing searches anymore 

### ISSUE THREAD

**Issue by Aryytt** [tmxkn1/Microsoft-Reward-Chrome-Ext#132]
- Do not report invalid user agents.
- Make sure you have read the troubleshooting before submitting a bug report.

----
**I have read the Troubleshooting**
Yes

**Describe the bug**
All of a sudden I get an error when the extension is trying to do searches. 

**Since when**
July 4th

**Screenshots**
![image](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/102674471/be8c7bbf-e248-42f3-81f4-a9fb01449988)

**U.S**

**Your web browser and OS**
Edge on Windows 11

**Additional context**
Had this issue before, I started using edge and the extension seemed to be working. Now I have the same issue.

**Comment by ivelweyz** [comment]
Had the same issue up until a few minutes ago. Clearing site data for bing/msn/microsoft/xbox/whatever else you use the account on, made it work again.

**Comment by reDpz** [comment]
> Had the same issue up until a few minutes ago. Clearing site data for bing/msn/microsoft/xbox/whatever else you use the account on, made it work again.

tried, no luck

**Comment by Aryytt** [comment]
@tmxkn1 The extension was working fine up until 2 days ago. It's only the mobile searches that are not working

**Comment by davidcafor** [comment]
> @tmxkn1 The extension was working fine up until 2 days ago. It's only the mobile searches that are not working

All the plugins I've been testing have the same problem with mobile searches. Hope Microsoft has made some changes over there.

**Comment by XxBAJNOKxX** [comment]
**The repo is not up to date with current useragents.**

- You can fork the repo, and change the useragents [here](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/master/useragents.json) and edit the utility.js file [here](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/8f265eb224915221e1ba7302f97db171c1ae422a/src/utility.js#L142) to your own github repo url: e.g.: `https://github.com/username/Microsoft-Reward-Chrome-Ext/blob/master/useragents.json`

OR if you don't want to, or don't know how, just download my repo and use it.

**Comment by AdamSzPL** [comment]
Still not working for me. it starts after chrome last update

**Comment by tmxkn1** [comment]
UA is always going to be an issue. MS may also closely monitor it to produce measures to counter bots like these. In a future version, I will provide a toggle to allow the use of the browser's native UA. The only problem with this is Edge search will not be registered if you are not using the Edge browser.
