### ISSUE TITLE
[error_type] Temporary issue with Microsoft Rewards.

### ISSUE THREAD

**Issue by B3lik0** [tmxkn1/Microsoft-Reward-Chrome-Ext#143]
- Do not report invalid user agents.
- Make sure you have read the troubleshooting before submitting a bug report.

----
**I have read the Troubleshooting**
Yes

**Describe the bug**
[Temporary issue with Microsoft Rewards #2](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/master/TROUBLESHOOTING.md#temporary-issue-with-microsoft-rewards-2)

**Since when**
More Than 3 days

**Screenshots**
![Sin título](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/63465245/85071fe3-5d58-4e86-9667-93e08d6bef7d)

**Your country**
Mexico

**Your web browser and OS**
Brave Versión 1.60.114 Chromium: 119.0.6045.124 (Build oficial)  (64 bits)
Windows 10 Pro Versión	22H2

**Additional context**
When is open the external devtool, it is working good, but inside the main browser does not work.
![Sin título](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/assets/63465245/c93c69c1-5eb0-406f-a9df-f2a2bdc05f5c)

**Comment by XxBAJNOKxX** [comment]
Same problem as [#142](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/142)

**Comment by antediluvian00** [comment]
Same problem here.

**Comment by XxBAJNOKxX** [comment]
Okay, so it looks like Microsoft has started using unique identifiers for searches.
Searches used by the extension do not contain these unique identifiers and are therefore not considered as valid searches.
