### ISSUE TITLE
Mobile search stopped working

### ISSUE THREAD

**Issue by throny** [tmxkn1/Microsoft-Reward-Chrome-Ext#15]
Hey there,

got a problem recently for the mobile search tasks.

This is what I get as errors:
![image](https://user-images.githubusercontent.com/11830644/130323358-32fb0607-a3a6-4a41-b2c1-4f50594fadd8.png)

Probably something changed, I have no clue what exactly. If I can provide more useful info let me know please!

**Comment by Emanuads** [comment]
I'm experiencing the same issue but the line marked in yellow it's different
![image](https://user-images.githubusercontent.com/89336657/130348355-4a2ae320-d64e-4630-b44f-1e6b1b703dbd.png)

**Comment by Tripticon84** [comment]
Same issue here (it dont farm mobile point) but the I don't get any error on my main PC. 
<img width="95" alt="Capture d’écran 2021-08-22 141844" src="https://user-images.githubusercontent.com/51379453/130354986-2ec57619-3bdf-4a9e-9e52-733ca730725c.png">


However on my laptop I get the same as @Emanuads

**Comment by tmxkn1** [comment]
try update to mbfix branch:

```
git switch mbfix
```

**Comment by throny** [comment]
Works like a charm, thank you for the quick fix @tmxkn1 !

**Comment by Tripticon84** [comment]
Thank you for the fixing ❤

**Comment by MugenDad** [comment]
Yes thank you very much for this quick fix

**Comment by tmxkn1** [comment]
Thanks all for confirming. The fix was found by Mooons and has been merged into the master branch.
