### ISSUE TITLE
Not fully working anymore - doesnt do mobile searches

### ISSUE THREAD

**Issue by Chimpinski** [tmxkn1/Microsoft-Reward-Chrome-Ext#19]
I've been using the extension for a while but since 2 days ago I noticed that it does the desktop and edge searches perfectly fine but doesnt do the mobile searches at all. The icon stays blue and just never does them.

**Comment by josekast** [comment]
me too

**Comment by 666dsa666** [comment]
Resolved : 
https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/pull/21

**Comment by Chimpinski** [comment]
> Resolved : 
> 
> https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/pull/21

Thank you!
