### ISSUE TITLE
Error - MS rewards has changed

### ISSUE THREAD

**Issue by MugenDad** [tmxkn1/Microsoft-Reward-Chrome-Ext#2]
signing out and signing back into MS rewards has not fixed the issue, is this fixable?

getting "fetch failed because redirection occurred" in the extension errors page

**Comment by MugenDad** [comment]
![Untitled](https://user-images.githubusercontent.com/54858915/64194632-a3f42180-ce4d-11e9-8b7f-728f1a06899a.png)

**Comment by tmxkn1** [comment]
> signing out and signing back into MS rewards has not fixed the issue, is this fixable?
> 
> getting "fetch failed because redirection occurred" in the extension errors page

Thanks for reporting the issue. I am also aware of this. I will look into it and fix it when I have time.

**Comment by MugenDad** [comment]
Error seems to be fixed, if you believe so as well you can close this issue, and thank you!
