### ISSUE TITLE
search are broken, useragents are not in cause

### ISSUE THREAD

**Issue by 666dsa666** [tmxkn1/Microsoft-Reward-Chrome-Ext#22]
No search seems to be done on my side.
I tried updating usqeragents once again, tried using my own useragents. None are working so this might not be the issue.

**Comment by 666dsa666** [comment]
So it started working but not completely.
After an hour I had 50% of the desktop search done and 100% of the mobile search without any changes.

**Comment by josekast** [comment]
The same thing happens to me.

**Comment by GppCalcagno** [comment]
mobile searches don't work for me (running of Edge 96.0.1054.62)

**Comment by 666dsa666** [comment]
> mobile searches don't work for me (running of Edge 96.0.1054.62)

did you update the extension ? There was an update less than a week ago resolving the issue. It's working for mobile on my side but only 50% of desktop search are working.

**Comment by 666dsa666** [comment]
Okay so search are made and bing is recording them but points are not counted.
On my side I updated the useragents once again but mixed the mobile and desktop useragents
Putting them where they should seems to have resolved the issue but I'll only be able to confirm tomorrow.
I'll keep you updated, if needed I'll try to update the extension so the desktop useragent is the one from your browser and if possible (I'm definitely not a dev) I'll try to get an up to date user agent, maybe a dropdown list to choose from for the mobile side.

**Comment by GppCalcagno** [comment]
> > mobile searches don't work for me (running of Edge 96.0.1054.62)
> 
> did you update the extension ? There was an update less than a week ago resolving the issue. It's working for mobile on my side but only 50% of desktop search are working.

I updated the addon and it work! sorry for the wrong segnalation

**Comment by 666dsa666** [comment]
> I updated the addon and it work! sorry for the wrong segnalation

Glad it worked, do you eventually have the same issue as #23 ? Just want to make sure as there are no other reports so far.

**Comment by GppCalcagno** [comment]
unfortunately the counter doesn't work for me either, many times from wrong or even negative values. For example now i have 50 missing points from daily quest and other 65 from others, but the counter marks only 65

**Comment by 666dsa666** [comment]
Useragents update solved the issue on my side, I'll do my best to have a working prototype before the end of the week.

**Comment by tmxkn1** [comment]
Hi All, Thank you all for reporting and contributing in this project.

> unfortunately the counter doesn't work for me either, many times from wrong or even negative values. For example now i have 50 missing points from daily quest and other 65 from others, but the counter marks only 65

I have not found this problem with my MSR accounts. Therefore, I would need some information from you to diagnose the issue. I've updated the extension to include a 'debug' button when you click the extension button. This will copy the necessary information, e.g. point status, quiz progress, etc. to your clipboard. You can review this information, remove anything you aren't comfortable to share and then post the copied text here.



> Useragents update solved the issue on my side, I'll do my best to have a working prototype before the end of the week.

Same, UA updates fixed mine and I don't have any issue with PC searches. Thank you very much.

**Comment by tmxkn1** [comment]
> Okay so search are made and bing is recording them but points are not counted. On my side I updated the useragents once again but mixed the mobile and desktop useragents Putting them where they should seems to have resolved the issue but I'll only be able to confirm tomorrow. I'll keep you updated, if needed I'll try to update the extension so the desktop useragent is the one from your browser and if possible (I'm definitely not a dev) I'll try to get an up to date user agent, maybe a dropdown list to choose from for the mobile side.
> 
> Actually it should be a dropdown for both as using chrome would not give the edge bonus

Using the browser's UA is a great idea. This should have been implemented from the start! I will let you make a pull request to credit your contribution properly. Cheers

**Comment by 666dsa666** [comment]
> I will let you make a pull request to credit your contribution properly. Cheers

I tried working on it almost all day long, but I am in no way a developper, let alone a good one...
I would say I'm 90% done as I can read the local useragent and have two textboxes to set new ones if needed
Sadly I can't seem to be able to store those values and let the script use them
I'll keep on adding the features I think are needed (language for google trend searches, autostart checkbox and variable wait time) but I'll probably take a few days if not weeks to get it to a working state as I am learning while working on it.
Feel free to use it if it can help.

**Comment by tmxkn1** [comment]
> > I will let you make a pull request to credit your contribution properly. Cheers
> 
> I tried working on it almost all day long, but I am in no way a developper, let alone a good one... I would say I'm 90% done as I can read the local useragent and have two textboxes to set new ones if needed Sadly I can't seem to be able to store those values and let the script use them I'll keep on adding the features I think are needed (language for google trend searches, autostart checkbox and variable wait time) but I'll probably take a few days if not weeks to get it to a working state as I am learning while working on it. Feel free to use it if it can help.

Thank you for your contribution again. 

I have no intention to add more features/options to this extension as it will complicate things with no significant benefit. However, do feel free to work on it and have your own branch with those features. That being said, I will likely decline your pull request if these additional features are included. Hope you can understand this.

To save and retrieve the parameters, take a look at my [previous implementation](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/fd665205ccc02e3ae43ee5142bd829e5f41f9b2a/src/popup.js).

**Comment by tmxkn1** [comment]
I believe several reports in this issue are related to useragent and now has been solved. Another issue has been open for discussion on adguard related.
