### ISSUE TITLE
Several problems

### ISSUE THREAD

**Issue by noc95x** [tmxkn1/Microsoft-Reward-Chrome-Ext#24]
Hi, 
I write from Europe.
I updated the add-on to the latest version (the one with the dubug button).
I use the windows 10 operating system and as a browser google chrome updated to the latest version available.
I have been using this add-on for several months and have never encountered any major problems.
However, in the last few weeks I have encountered some problems:
1) After completing all the daily daily searches (from Mobile and desktop PC) and the daily quests, the counter remained yellow indicating a negative value. In the first half of December -100 and in the second half of December -50. This problem has been encountered with the 100-point or 150-point quest which must be completed within a certain period (usually 3-4 weeks).
A similar problem with the counter occurred when the quest of "this and that" was not completed correctly (quest where you have to choose between two alternatives 10 times and receive 5 points for each correct answer).
Ex: if the correct answers were 9 out of 10, the add-on's wave remained yellow indicating a value of 5. The "this and that" quest remains available for about a week and the add-on icon remains for the entire period yellow indicating, in the example, the value 5.
2) For about a week the add-on has not been able to process daily searches, initially only "searches from PC" and then also "searches from mobile devices" and "microsoft edge bonus".
The add-on icon remains blue and you may encounter the following problems:
- does not allow you to carry out daily quests that involve user interaction such as "bonus quizzes" or "daily surveys". With the add-on active by opening the hyperlink, the pop-up does not appear at the bottom where you can click. At the moment the add-on is blocked it is possible to complete the daily quests.
- As long as the add-on remains active it is not possible to search through the bing search engine, you get the following error: "Ref A: [...] Ref B: [...] Ref C: [...] ". These are however counted by the MSR as searches from PC.

I don't speak English well and I don't know if the names used in Europe to indicate the different activities to be carried out to get the points are the same as those used in the USA.
Thanks for the work done.
Happy Holidays

**Comment by 666dsa666** [comment]
Hello,
1, please use newest version and post the debug info in #23 

2, Updated version should resolve it, I'm working on getting it to be more futureproof in #22
