### ISSUE TITLE
Adguard compatibility

### ISSUE THREAD

**Issue by tmxkn1** [tmxkn1/Microsoft-Reward-Chrome-Ext#28]
If using adguard something definitely changed as turning it on stop the extension from working, turning it off makes it work immediately.
It looks like "c.bing.com or bat.bing.com" might be the wrongfully blocked domain name, I'll check tomorrow if it's either one, the other or something else.

_Originally posted by @666dsa666 in https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/25#issuecomment-1003978459_

**Comment by 666dsa666** [comment]
Unblocking c.bing.com did solve the issue.
No need for bat.bing.com unblocking.
