### ISSUE TITLE
Mobile searches aren't cleared

### ISSUE THREAD

**Issue by ChiaraM96** [tmxkn1/Microsoft-Reward-Chrome-Ext#29]
Since this morning, the mobile searches counter isn't updated. I tried logging out and back in, to no avail. I also tried the compatibility mode. 
Whenever I hit the 'check now' button, it either shows the red error icon, or the blue icon. 
I'm running the latest version of the extension on MS Edge.

**Comment by tmxkn1** [comment]
Have you updated the extension? The newest version doesn't have a check now button.

**Comment by ChiaraM96** [comment]
> Have you updated the extension? The newest version doesn't have a check now button.

Aaand that did it. I think I accidentally loaded an old copy of the repository, instead of the updated version. Typical of me. Sorry and thanks!

**Comment by ChiaraM96** [comment]
> Have you updated the extension? The newest version doesn't have a check now button.

I *thought* I had installed the latest update, turns out I didn't. I updated the extension, but the problem persists.

**Comment by d4rkdev-it** [comment]
Same problem, extension updated

**Comment by davidkast** [comment]
Same problem, thanks

**Comment by adriangc13** [comment]
Same here

**Comment by Tripticon84** [comment]
Same here.

The [debug text](https://gist.github.com/Tripticon84/323b7cccafd0a3992a30c171b4c473a9) (don't know if it can help)

**Comment by tmxkn1** [comment]
It was a problem with the mobile user agent... The iOS Edge wasn't recognised by bing, I wonder why.

I've patched it in the [new release](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/releases/tag/v2.23.1).

Thanks all for reporting.
