### ISSUE TITLE
mobile queries arent performed

### ISSUE THREAD

**Issue by Speil** [tmxkn1/Microsoft-Reward-Chrome-Ext#33]
Hi,
since today the rewards for mobile queries are stuck at 0/60. Desktop and edge queries are all collected. After a few minutes, the script shows the red error logo.

I'll watch, maybe its solving itself during the day

**Comment by drmaernardi** [comment]
Same here. Everything else completed but the mobile searches, shows 'err' after a while.

**Comment by 666dsa666** [comment]
Issue is on the useragent script has even though the script seems to have ran really recently the list is actually not updated.

**Comment by tmxkn1** [comment]
Thanks all for reporting. It was a bug in the [UpdatedUserAgents](https://github.com/tmxkn1/UpdatedUserAgents). I have patched it locally and updated the UA in the repo. All seems work now.
