### ISSUE TITLE
PC Search and EDGE Search doesn't work.

### ISSUE THREAD

**Issue by TrialMacameau** [tmxkn1/Microsoft-Reward-Chrome-Ext#34]
Extension caught 2 exception errors and couldn't get the PC Search and the Edge Bonus

https://cdn.discordapp.com/attachments/589596768165953559/947044812597657620/Screenshot_33.jpg
https://cdn.discordapp.com/attachments/589596768165953559/947044812832514068/Screenshot_34.jpg

**Comment by 666dsa666** [comment]
Useragent has been updated.

You can **Temporarly** update utility.js to use 
https://raw.githubusercontent.com/666dsa666/UpdatedUserAgents/master/useragents.json
I will probably not update it or run the script unless I really need it and will be back to tmxk1n version as soon as the script has been ran.
(I have no idea how many things on github works but I believe some scripts can be ran automatically by github servers that may be an idea ?)

Another way would be forking the script from tmxkn1 and run it yourself and update the same file (utility.js) to route the script to your fork.

tmxk1n made it really easy to maintain and update so you should ;)

**Comment by TrialMacameau** [comment]
Much appreciated. Maybe I should.

**Comment by steverethink** [comment]
first of all, thanks for the updated useragents.json @666dsa666. seems to be working just fine.

@TrialMacameau you shouldn't have to install python or do anything of the sort. you just need to update the url thats inside utility.js. 

if you still have the extension downloaded, just /src/utility.js and change the json file url on line 106 to this:

`    const fetchProm = fetch('https://raw.githubusercontent.com/666dsa666/UpdatedUserAgents/master/useragents.json', {method: 'GET', signal: signal});
`

save it, and then re-install the extension. it should work again. its a temp fix obviously until the main repo is updated.

**Comment by tmxkn1** [comment]
> I believe some scripts can be ran automatically by github servers

Could be an awesome idea. I haven't looked into this, but there is Github action that might do something like this. I know there are third-party services that can do this too but may involve payment. I need to allocate time to look into this.
