### ISSUE TITLE
Problem with the bot

### ISSUE THREAD

**Issue by noc95x** [tmxkn1/Microsoft-Reward-Chrome-Ext#35]
Hello,
The bot that has been working properly for several months suddenly fails. This is no longer able to complete daily searches both "from PC", "from mobile" and "from EDGE".
The bot icon turns red with the word "err".
Going to the chrome extensions manager I get the following errors:
Error 1:
Access to fetch at 'https://login.windows.net/ (long link I didn't copy) has been blocked by CORS policy: No' Access-Control-Allow-Origin 'header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Error 2:
Uncaught (in promise) FetchFailed :: FetchFailed :: TypeError: Are we redirected by the old URL too? Report to the author now! InnerEx: FetchFailed :: TypeError: Are we redirected? InnerEx: TypeError: Failed to fetch
Error 3:
Uncaught (in promise) ParseJSONFailed: Empty json received. InnerEx: null

I noticed that using another PC, the same account and the same LAN connection I get the same errors. If, on the other hand, I use a different data connection (that of the smartphone), with the same account and the same PC, the bot does not give any errors.

**Comment by Necrownyx** [comment]
This is being caused because you did not follow the steps to log into Microsoft rewards and Bing try going to [Bing](https://bing.com) and [Microsoft Rewards](https://rewards.microsoft.com/) and check that you are logged into both with your Microsoft account and try again.
