### ISSUE TITLE
afk farm button 

### ISSUE THREAD

**Issue by FRKFFR** [tmxkn1/Microsoft-Reward-Chrome-Ext#38]
hello I just had an idea is it possible to add an afk farm button to avoid coming to click to update the extension every day, (farm with several accounts to do an automatic farm)

**Comment by tmxkn1** [comment]
This is not possible with a browser extension. [This python-based bot](https://github.com/tmxkn1/Microsoft-Rewards-Bot) may work for you.

**Comment by FRKFFR** [comment]
But why an extension called ABS has a programming button for the time and it works but I run a computer tablet all the time is your extension updated I don't it's not if it's Edge that does this automatically

**Comment by tmxkn1** [comment]
If you open multiple browsers with each browser logged into a different account, then yes it does the searches automatically.

All this extension does is do some bing search for you. It does not and cannot log into your account with your password.
