### ISSUE TITLE
extension not doing pc searches and preventing manual searches

### ISSUE THREAD

**Issue by Chimpinski** [tmxkn1/Microsoft-Reward-Chrome-Ext#39]
extension only doing mobile searches, also when extension is enabled, the searches I do manually arent counting towards points. After I disable the extension, I can do manual searches.

**Comment by tmxkn1** [comment]
This sounds exactly like a UA issue which is explained [here](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/36#issuecomment-1078264853)
