### ISSUE TITLE
Kinda not working

### ISSUE THREAD

**Issue by Leutonia** [tmxkn1/Microsoft-Reward-Chrome-Ext#41]
I just installed the extension in Edge. 
Shows the remaining points but does nothing.... 
Also you stated, that there is a "check now" button. I can't find it. Icon is yellow all the time since a few hours.

Thanks!

**Comment by tmxkn1** [comment]
The check now button has been removed and all the background work is executed as soon as you click the extension. The extension does not do anything else apart from completing all the search quests (PC, Edge and mobile) and displays the remaining points.
