### ISSUE TITLE
Won't complete searches, getting error logo on the extension logo

### ISSUE THREAD

**Issue by jp6654** [tmxkn1/Microsoft-Reward-Chrome-Ext#42]
If I go to extensions and check error it has plenty of different errors, that even after being cleared reappear after opening the extension, and none of the searches are being completed.

**Comment by tmxkn1** [comment]
Can you give some examples of the errors? Either screenshots or copy and paste.

**Comment by jp6654** [comment]
Access to fetch at 'https://login.windows.net/consumers/oauth2/v2.0/authorize?client_id=9c941f7c-a811-4e9c-8e66-29fdec50490f&redirect_uri=https%3A%2F%2Frewards.microsoft.com%2Fsignin-oidc&response_type=code&scope=openid%20profile%20offline_access&response_mode=form_post&nonce=637848772198033589.YWYxZmU5NjAtZmQzNi00NDYyLTg2NGQtMjljN2Y3OWU4OTJhYTY2ZjkwMmEtNzQxZC00YmYxLThjNzctMWUxZjRiMTBmYWE1&client_info=1&x-client-brkrver=IDWeb.1.9.1.0&lw=1&fl=easi2&cobrandid=03c8bbb5-2dff-4721-8261-a4ccff24c81a&state=CfDJ8Lo-QAV7_udIjvv8ZLI8oSTA2lq2ev1SJbFNp6fcsGPs0ATjPZx-j61kxrZUP6QN__LYOg9t9nY8_vDmzi9WJ0939VjakRyIqfS-k0anVWTECT4RPUx6S2Eu_0C0HIwYp-QJu-jAXOMV5sspnzO3qRu9uOyjucdAfAFUb71t7b9rQvhT53RYgbsafwhQFOgnRPrN5Z5mpwb-AOlFBV7hpwZzpn508etUjWf0kUkgJypsm2lVnm3ko4tsNLiqWV1ob1Tq5MYicWY3nWG9NoyukRHv1HArg3gk6-J8ETVJQs8O6M9-8K7BMiPJd8L7LaSIbalux-0PPab4ca2a5hUAthg&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.1.0' (redirected from 'https://rewards.microsoft.com/pointsbreakdown') from origin 'chrome-extension://gjodciddclgfgdlpfmkianbgkjhfgpem' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)
Nothing to see here, move along.
Access to fetch at 'https://login.windows.net/consumers/oauth2/v2.0/authorize?client_id=9c941f7c-a811-4e9c-8e66-29fdec50490f&redirect_uri=https%3A%2F%2Frewards.microsoft.com%2Fsignin-oidc&response_type=code&scope=openid%20profile%20offline_access&response_mode=form_post&nonce=637848772205264468.NWQ4NDcyOWUtZTU2ZS00OTM3LWI3YzMtODBiMTA3NGY1NjQ1ZGQyODRkMzctMzQ1ZS00YjE5LWFhYzctMmQ3NDJlY2JiMmMw&client_info=1&x-client-brkrver=IDWeb.1.9.1.0&lw=1&fl=easi2&cobrandid=03c8bbb5-2dff-4721-8261-a4ccff24c81a&state=CfDJ8Lo-QAV7_udIjvv8ZLI8oSQxmdiW-KNvmJhhYOQRmOJ_4gJVVvFyGCOI7l31NaougoAeeS09FtenJhpJcGdaHTU_M2uWfs6iQPVdGdZU_cVd2slQFhAI_kJCI2EBYX11AEbnCNX8egwmcY0Av2s6LSDTOfr5rV67h18kxZ10_bAQ1LYPwcmjZHAm7R5I8O7iO4WZIitU9jZZGgHP391v3cvl--2X709pDdZx9r6NQL-1J6tXOTcOOdd1JfUYjHiMlAGN53CMF0VAtmaYEOoosBYsglTNZSdsqIWgeb9LiRHEHOObeQg_DVWavlzVlws_yvpQNVPU28hUrL1s2wMrBXIB8veQ3x_733LBOOeXE6Fx&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=6.10.1.0' (redirected from 'https://account.microsoft.com/rewards/pointsbreakdown') from origin 'chrome-extension://gjodciddclgfgdlpfmkianbgkjhfgpem' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Uncaught (in promise) FetchFailed::FetchFailed::TypeError: Are we redirected by the old URL too? Report to the author now! InnerEx: FetchFailed::TypeError: Are we redirected? InnerEx: TypeError: Failed to fetch

**Comment by tmxkn1** [comment]
Thanks.
Have you logged into MS reward? Which branch are you using?

**Comment by jp6654** [comment]
Yes, I have. By branch you mean?

**Comment by jp6654** [comment]
Here's a picture: https://prnt.sc/CuMas7EChjNa

**Comment by tmxkn1** [comment]
> Yes, I have. By branch you mean?

![image](https://user-images.githubusercontent.com/8778250/162083550-eb90f122-dead-4ba0-a739-701b795e2fff.png)

If you don't know about branch, I suppose you are using 'master'.

Can you click the following links and let me know if it takes you to a login page or rewards dashboard?

[https://account.microsoft.com/rewards/pointsbreakdown](https://account.microsoft.com/rewards/pointsbreakdown)
[https://rewards.microsoft.com/pointsbreakdown](https://rewards.microsoft.com/pointsbreakdown)

**Comment by jp6654** [comment]
First link is an error, second link brings me to the menu where it tells you about where you earned your points.

**Comment by jp6654** [comment]
Oh now its working, I don't know what happened but thank you anyways! Also special thanks for the extension I've already been using it for a while now.

**Comment by tmxkn1** [comment]
> First link is an error, second link brings me to the menu where it tells you about where you earned your points.

What is the URL you actually arrive at after the page is fully loaded using the second link?
Perhaps, try [stable-ua branch](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/tree/stable-ua)

**Comment by tmxkn1** [comment]
> Oh now its working, I don't know what happened but thank you anyways! Also special thanks for the extension I've already been using it for a while now.

Glad to know! Perhaps, the cookie for the rewards page expired and the logging status needs to be refreshed by visiting the page once again.
I will see if this can be avoided.
