### ISSUE TITLE
Continuous error display for new version

### ISSUE THREAD

**Issue by LeFlairGoD** [tmxkn1/Microsoft-Reward-Chrome-Ext#47]
Hello,
first of all thank you for the nice Extension.
I have just downloaded the new version 2.24.1 and installed.
However, I consistently get the red error icon displayed.
The old Versio still works very well for me, have the first reinstalled! 2.24.0

Greetings

Here is the error message
![image](https://user-images.githubusercontent.com/64659197/166146121-62e703a0-2957-4ba4-b210-1deea43a9c5b.png)
![image](https://user-images.githubusercontent.com/64659197/166146211-6c866641-0b73-41ed-813d-ba34a1270798.png)

Just see, the automatic rewards do not work either
![image](https://user-images.githubusercontent.com/64659197/166194997-cbb06b98-39df-453c-aa8f-869b4b1765a9.png)

**Comment by ChiIIerr** [comment]
I am also receiving this error

**Comment by Emanuads** [comment]
Me too

**Comment by Speil** [comment]
same here

**Comment by SsimplyDan** [comment]
yh same

**Comment by FRKFFR** [comment]
use Microsoft Edge

**Comment by SsimplyDan** [comment]
alr

**Comment by LeFlairGoD** [comment]
> use Microsoft Edge

No Thanks

**Comment by icase81** [comment]
> use Microsoft Edge

I am using Edge, and still get the error. 2.24.0 works fine, 2.24.1 does not.

> Uncaught (in promise) ParseJSONFailed: Fail to parse the received json document. Has MSR updated its json structure? InnerEx: TypeError: Cannot read properties of null (reading 'promotionType')



> Context

> extension://bgodbankkcableilakajbiaceeeflpef/_generated_background_page.html

> Stack Trace

> status/DailyRewardStatus.js:208 (DailyRewardStatus._parsePunchCards)
status/DailyRewardStatus.js:194 (DailyRewardStatus._parseDetailedUserStatus)
status/DailyRewardStatus.js:58 (DailyRewardStatus.update)
background.js:89 (async checkDailyRewardStatus)
background.js:68 (async doBackgroundWork)


Seems to be in this line 208:

`            const promoTypes = card.parentPromotion.promotionType.split(',');
`

**Comment by tmxkn1** [comment]
Hi All,

Thanks a lot for reporting. I just managed to get back from a holiday. I've pushed a fix for this error. All should be resolved now!
