### ISSUE TITLE
Still use version 2.24.0 new version still error message and does not count the full points

### ISSUE THREAD

**Issue by LeFlairGoD** [tmxkn1/Microsoft-Reward-Chrome-Ext#48]
Hello,
after your pull-request I loaded the new version again, but it still doesn't work 100%. It counts the points, but not completely.
Have changed back to version 2.24.0, there everything works fine except for the info icon. The lights continuously yellow.

Thanks for your great work

Unfortunately I don't have an error message right now, but I can add it if necessary.

**Comment by tmxkn1** [comment]
> it still doesn't work 100%. It counts the points, but not completely.

Does it show the red error icon or does it show a yellow icon with points but miss some values?

**Comment by LeFlairGoD** [comment]
> > it still doesn't work 100%. It counts the points, but not completely.
> 
> Does it show the red error icon or does it show a yellow icon with points but miss some values?

It show the red error icon

**Comment by tmxkn1** [comment]
Did you do a pull or downloaded the package from release? I have not yet published a release.

**Comment by LeFlairGoD** [comment]
Ah fail, i have downloaded the release. 😅

**Comment by tmxkn1** [comment]
The issue has been fixed in the latest release. Thanks all for reporting.
