### ISSUE TITLE
Uncaught (in promise) ParseJSONFailed: Fail to parse the received json document. Has MSR updated its json structure? InnerEx: TypeError: Cannot read properties of null (reading 'promotionType')

### ISSUE THREAD

**Issue by FlubbedMammal13** [tmxkn1/Microsoft-Reward-Chrome-Ext#49]
![image](https://user-images.githubusercontent.com/86851477/166984827-3edee268-66b9-4fb5-b482-3fb178078074.png)

Works on some of my accounts but a few i'm getting this error

**Comment by tmxkn1** [comment]
Please update to the latest push.

**Comment by tmxkn1** [comment]
issue fixed in the latest release
