### ISSUE TITLE
Mobile searches stopped working

### ISSUE THREAD

**Issue by Emanuads** [tmxkn1/Microsoft-Reward-Chrome-Ext#50]
EDIT:
Well, pretty strange it's working now... I will leave this open in case someone is still experiencing the same issue

Hello, today I started getting this error while running the extension:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/89336657/167286552-e040e66b-3f7e-4232-9219-d63eed77f038.png">

Anybody else experiencing the same?

**Comment by tmxkn1** [comment]
> I believe this is caused by a small mistake in utility.js :
> 
> > ```
> >             userAgents.mb = ua.chrome.chrome_ios;
> > ```
> 
> should be `userAgents.mb = ua.chrome.ios;`
> 
> EDIT : To be clear, from what I understand this would actually set the mobile useragent to "" which would cause the issue you're getting while thinking the useragent has been updated and shoudl be working.

Thanks you are very correct about the error.

**Comment by tmxkn1** [comment]
fixed in the latest push, will be published in the next release.
