### ISSUE TITLE
Red error/other

### ISSUE THREAD

**Issue by kodenamekrak** [tmxkn1/Microsoft-Reward-Chrome-Ext#54]
currently on 2.24.1.2 and logging into rewards.microsoft.com will show the extension as it should once, and the same with rewards.bing.com. after it has shown once it sometimes goes to red error and always just shows either the bing homepage or this 
![Screenshot 2022-05-29 104140](https://user-images.githubusercontent.com/106346717/170862072-22bf5636-5da3-49d1-bb2d-3efb2cb319e6.JPG)

**Comment by tmxkn1** [comment]
Can you show a screenshot of [https://rewards.bing.com/pointsbreakdown](https://rewards.bing.com/pointsbreakdown)? Feel free to pixelate any sensitive information.

**Comment by kodenamekrak** [comment]
![image](https://user-images.githubusercontent.com/106346717/171005360-8265ead1-a132-497e-9282-8110872f7f9f.png)

**Comment by tmxkn1** [comment]
This is weird :( Looks like everything is normal though. When you do a search on bing.com, does it register points? 

Can you also go to the extension's option and click the copy debug info? It should place a long text on your clipboard, just past the text on [https://pastebin.com/](https://pastebin.com/) and share the link here.

**Comment by kodenamekrak** [comment]
https://pastebin.com/KTZiMhjE

**Comment by kodenamekrak** [comment]
During this time of the extension not working, microsoft rewards was also having difficulties tracking my task progress, but as of today that issue along with the extension red error seems to be gone, so it may have been a microsoft issue rather than extension issue

**Comment by tmxkn1** [comment]
Ah thanks for reporting back. Sorry I've been on holiday and missed the notification completely. Glad it has been resolved on your end.
