### ISSUE TITLE
Cannot find working UAs

### ISSUE THREAD

**Issue by jsongo21** [tmxkn1/Microsoft-Reward-Chrome-Ext#55]
## Description

I've been stuck on the blue badge for the last couple of days and then occasionally a red badge with an error will pop up.

![image](https://user-images.githubusercontent.com/29261202/172085142-17c464b6-a7da-4264-b476-974437d6b5aa.png)

I found this when inspecting the extension. Looks like I'm having issues with user agents.
![image](https://user-images.githubusercontent.com/29261202/172085082-c4d0dbce-f7a0-4f16-b7d5-4cd1fd917443.png)

[Debug Info](https://pastebin.com/Ju4u2sRm)
## Details
* Mac OS 12.3.1
* Chrome 102.0.5005.61 (arm64)
* Extension ver 2.24.1.2

**Comment by tmxkn1** [comment]
I will add an option for users to configure UA by themselves. It seems difficult to find a robust way of managing the UA.

**Comment by tkon99** [comment]
You could always use this API and a daily Github action to update the JSON in this repo.
https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome
https://www.whatismybrowser.com/guides/the-latest-user-agent/edge

Alternatively you could have the extension scrape these pages.

**Comment by tmxkn1** [comment]
> You could always use this API and a daily Github action to update the JSON in this repo. https://www.whatismybrowser.com/guides/the-latest-user-agent/chrome https://www.whatismybrowser.com/guides/the-latest-user-agent/edge
> 
> Alternatively you could have the extension scrape these pages.

Yes, to keep things cleaner, scraping is in [UpdatedUserAgents](https://github.com/tmxkn1/UpdatedUserAgents) and the extension retrieves the result from there.

**Comment by foussix** [comment]
hello , today i get the same error , Cannot find working UAs , any fix for this error please. thank you

**Comment by RoyEastmen** [comment]
> I will add an option for users to configure UA by themselves. It seems difficult to find a robust way of managing the UA.

Do you know when this will be added?

**Comment by tmxkn1** [comment]
> > I will add an option for users to configure UA by themselves. It seems difficult to find a robust way of managing the UA.
> 
> Do you know when this will be added?

Added in the lastest update.

**Comment by foussix** [comment]
hello Roy , please i want to ask about the extension , it's not working
anymore or it's from my side , any update or change i need to do on my side
?

Le dim. 16 avr. 2023 à 11:27, Anthony Jiang ***@***.***> a
écrit :
