### ISSUE TITLE
Error CORS policy

### ISSUE THREAD

**Issue by MugenDad** [tmxkn1/Microsoft-Reward-Chrome-Ext#6]
logged in and when checking the icon is blue for a few minutes then throws this error:

"Access to fetch at 'https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1623898603&rver=7.0.6738.0&wp=MBI_SSL&wreply=https%3A%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signin%3Fru%3Dhttps%253A%252F%252Faccount.microsoft.com%252Frewards%252Fpointsbreakdown&lc=1033&id=292666&lw=1&fl=easi2' (redirected from 'https://account.microsoft.com/rewards/pointsbreakdown') from origin 'chrome-extension://lbehmgiofcogabfalnlbpfbcmafmmopd' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

**Comment by tmxkn1** [comment]
Have you logged into your MS account?

**Comment by MugenDad** [comment]
Yes, should I log out and then log back in using the “Microsoft rewards” button? I’m on the latest version btw

**Comment by tmxkn1** [comment]
> Yes, should I log out and then log back in using the “Microsoft rewards” button? I’m on the latest version using Brave browser btw

Has the extension worked before? Clearing cache and related cookies might help. I do not have Brave browser so I can't test it.

**Comment by MugenDad** [comment]
Yes, it was working for months but I’m also getting the same error on Chrome. I’ll try clearing cache and cookies
