### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by LeFlairGoD** [tmxkn1/Microsoft-Reward-Chrome-Ext#60]
Hello,
since a few days the extension does not work properly. When clicking on the "tasks" nothing happens, you have to click very often, so that he open the pages.
Then today I added the pull request, after that 4 error messages came.
Edit: 
Okay, had probably 6 error messages in the last 5 minutes now.
Meanwhile, it has leveled off to 3 (I am logged in to Bin and Rewards):

![image](https://user-images.githubusercontent.com/64659197/175893682-1e2bda39-fe69-426d-8db7-34988702cf53.png)
-------------------
![image](https://user-images.githubusercontent.com/64659197/175893877-288f9ad8-d406-4c55-ad11-1173647eb693.png)
--------------------------
![image](https://user-images.githubusercontent.com/64659197/175893903-af25a443-6502-4930-931d-8bc35afa5e17.png)
---------------------
![image](https://user-images.githubusercontent.com/64659197/175893925-b9d7eae4-8e65-41a7-9b8e-a3913ca6f2c3.png)

If you need more info, feel free to let me know.

**Comment by 666dsa666** [comment]
Not an extension issue, Microsoft have issues with the website. You'll have the same difficulty doing the tasks manually.

**Comment by LeFlairGoD** [comment]
All error messages are gone.
