### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by LittleBigMan81** [tmxkn1/Microsoft-Reward-Chrome-Ext#61]
Today when I logged in all I got was a red "err" icon and a message that said an update was available

I have installed the latest version and the red error icon persists.

**Comment by LeFlairGoD** [comment]
Did you accept the pull request? After that it worked for me.
Otherwise you should give more detailed information, only then you can be helped.
Which version did you install,
What are the errors ect.

**Comment by 666dsa666** [comment]
Not an extension issue, Microsoft have issues with the website. You'll have the same difficulty doing the tasks manually.

**Comment by drsurfer** [comment]
> Not an extension issue, Microsoft have issues with the website. You'll have the same difficulty doing the tasks manually.

Exactly. Even the quiz section is painfully slow and requires multiple attempts to get the points

**Comment by 666dsa666** [comment]
Issue seems to be solved on my side, though reddit seems to say that each region might have different servers and issues.
Hopefully it's fixed for everyone.

**Comment by LittleBigMan81** [comment]
I'm the Op and it seems my issue has been resolved.

Yesterday neither the bot nor the default MS rewards website was working properly.  At first, I thought this was an issue with the new bot update playing mary hob (yes that's a Firefly reference!) with the Rewards site.  I left it for 24 hours and logged back in today.

The bot seems to be working perfectly so far and I can now complete my daily Rewards quizzes and polls as well.  My guess is the issue was on the Microsoft side of things and not the actual bot.  

I'm not exactly a "power user" so after turning it on and off didn't work i decided to post here for more insight.  Sorry if my post was a little premature and thank you to the developer for the great extension and for all those who commented with suggestions.

**Comment by tmxkn1** [comment]
@LittleBigMan81 you can always report any issues, whether or not it temporarily affects you or not. We can never be more careful :)
