### ISSUE TITLE
Microsoft Rewards Extension always says "Extension Update Available"

### ISSUE THREAD

**Issue by Andrew1644563** [tmxkn1/Microsoft-Reward-Chrome-Ext#65]
Recently, the extension has been always saying that there is an update available, but I have already updated to the most recent version. Will this affect performance?

**Comment by Tyler2P** [comment]
I believe the issue to be caused due to the [manifest.json](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/blob/master/src/manifest.json) being a version ahead of the actual chrome extension. This will be automatically fixed in the next update.

**Comment by tmxkn1** [comment]
Hi yes, that is the issue. sorry for the unpolished master push. This should be fixed now.
