### ISSUE TITLE
PC and Mobile Searches Error 

### ISSUE THREAD

**Issue by Aryytt** [tmxkn1/Microsoft-Reward-Chrome-Ext#67]
![image](https://user-images.githubusercontent.com/102674471/177539327-9e2a04a5-dc0a-4df9-9aec-a9fb0602528c.png)

PC and mobile searches are not working and I'm on the latest version. I attached the error message I got.

**Comment by tmxkn1** [comment]
I updated UA, hopefully this will work but needs a day or more to test.

**Comment by Aryytt** [comment]
It worked for me right now. Thank you so much.

**Comment by TrialMacameau** [comment]
I had that issue recently but it seems you fixed it. :)

**Comment by Aryytt** [comment]
> No issues on my end.

What version do you have?

**Comment by Aryytt** [comment]
It seems to be working now for me.

**Comment by tmxkn1** [comment]
UA problems come and go usually. Unfortunately I'm pretty tied up with my work so have not yet got time to implement a better solution to this.
