### ISSUE TITLE
Error "Cannot find working UAs for pc and mobile"

### ISSUE THREAD

**Issue by Daitan9** [tmxkn1/Microsoft-Reward-Chrome-Ext#68]
I now get these errors, "Uncaught (in promise) UserAgentInvalid: Cannot find working UAs for pc and mobile."

And "Uncaught (in promise) UserAgentInvalid: Cannot find a working UA for mobile."

[https://imgur.com/a/2p3huom](url)

This is in the last commit Github shows, hope it can be fixed !

**Comment by tmxkn1** [comment]
Hi, do you still experience the same issue now?
