### ISSUE TITLE
[Bug] Error badge; not working at all

### ISSUE THREAD

**Issue by Jawman2000** [tmxkn1/Microsoft-Reward-Chrome-Ext#69]
I use Microsoft Edge. Been having to do Microsoft rewards manually for a while since this extension has stopped working. The error button is always there. If I click on it then it turns blue for a second and then goes back to red.

[https://imgur.com/a/I6kGWHj](url)

**Comment by dexavali** [comment]
Experiencing this too in both Chrome and Opera (GX), it just isn't working anymore for me.

**Comment by tmxkn1** [comment]
Hi, do you still experience the same issue now?
