### ISSUE TITLE
Access to fetch at 'https://login.windows.net/consumers/oauth2/v2.0/authorize?client_id=

### ISSUE THREAD

**Issue by ghost** [tmxkn1/Microsoft-Reward-Chrome-Ext#72]
Access to fetch at 'https://login.windows.net/consumers/oauth2/v2.0/authorize?client_id=

(redirected from 'https://rewards.bing.com/') from origin 'chrome-extension://agabinmnkdikcfpoheccgnolecngccgm' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

This pops up in developer console from errors tab

![Capture](https://user-images.githubusercontent.com/105869898/187077930-7289f95b-66cc-46f5-b024-2213af3e55f4.PNG)

**Comment by tmxkn1** [comment]
You may need to visit https://rewards.bing.com/ and log in.
