### ISSUE TITLE
Only information

### ISSUE THREAD

**Issue by LeFlairGoD** [tmxkn1/Microsoft-Reward-Chrome-Ext#73]
Sometimes, mostly when there is a WLAN change, these error messages occur.
I can only fix them if I delete the errors and restart the extension.
After every browser restart I have to do it like this.
Should now only serve as info, so no urgent need to fix the error on my part.
Top work, thank you for it. Keep it up!

![image](https://user-images.githubusercontent.com/64659197/188116152-f7039ce6-067d-4aab-960b-4eab8ab42dbd.png)
![image](https://user-images.githubusercontent.com/64659197/188116548-ff16fc1f-5ea4-4d5a-afe4-c7318776b017.png)
![image](https://user-images.githubusercontent.com/64659197/188118266-de7d1264-f226-491b-9373-3b9177a31d7a.png)

**Comment by 666dsa666** [comment]
I have the same issues for a few secs/minutes when a lan issue appear and resolve itself.
I believe this might be caused by some cache and some keepalive settings but I am pretty sure it's not an extension issue and something that can be solved on this side.
