### ISSUE TITLE
Extension doesn't work after updating to chrome 105

### ISSUE THREAD

**Issue by FuryCraft** [tmxkn1/Microsoft-Reward-Chrome-Ext#74]
Since the new chrome version the extension only returns errors "Are you logged into Microsoft Rewards / Bing" but I'm already connected

**Comment by LittleBigMan81** [comment]
I've been using MS Edge for well over a year now and have had zero issues with the bot.  Any time issues have arisen it's been on the MS Rewards side of things.

Also. my PC is happy I completely removed Chrome, its runs much smoother.

Edge is based on Chrome so to install the bot just follow the same set of instruction for setting it to developer mode.

**Comment by 666dsa666** [comment]
Chrome is getting harder and harder to work with and it will definitely not be easier as time passes by.
Using Edge might not be the solution for everyone sadly.
Though you can install the previous chrome version and confirm if it works or not, if it does I'll have a look at the exact changelog and try to find a way (if possible)

**Comment by FuryCraft** [comment]
Ok I tried on an other version and it does'nt work or complete some search but not all. Maybe they Microsoft change something on it side

**Comment by LittleBigMan81** [comment]
> Chrome is getting harder and harder to work with and it will definitely not be easier as time passes by. Using Edge might not be the solution for everyone sadly. Though you can install the previous chrome version and confirm if it works or not, if it does I'll have a look at the exact changelog and try to find a way (if possible)

Edge stopped working for me today as well (9/6) after working the previous day no problem (Edge Version 105.0.1343.27).

Just an FYI, hopefully you can work something out, thanks for all the hard work!

**Comment by 666dsa666** [comment]
Issues are ongoing and the extension is not in cause : https://www.reddit.com/r/MicrosoftRewards/comments/x7bgth/anyone_else_having_problems_with_bing_mobile_mine/
