### ISSUE TITLE
Showing Error (red)

### ISSUE THREAD

**Issue by gianniskapta** [tmxkn1/Microsoft-Reward-Chrome-Ext#76]
It's showing Error (red) and cannot give point.

**Comment by gianniskapta** [comment]
> Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.

I've checked it and completed some daily task but it's till showing the red error.

**Comment by 666dsa666** [comment]
> > Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.
> 
> I've checked it and completed some daily task but it's till showing the red error.

Because issues on rewards side are still ongoing :)

Issue seems to impact Xbox version too so definitely on Microsoft side : 
https://www.reddit.com/r/MicrosoftRewards/comments/x76mg9/ive_got_issues_with_my_rewards/

**Comment by gianniskapta** [comment]
> > > Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.
> > 
> > 
> > I've checked it and completed some daily task but it's till showing the red error.
> 
> Because issues on rewards side are still ongoing :)
> 
> Issue seems to impact Xbox version too so definitely on Microsoft side : https://www.reddit.com/r/MicrosoftRewards/comments/x76mg9/ive_got_issues_with_my_rewards/

Okay, gonna check it later in the day. It worked fine yesterday but today got bad with the error notification.

**Comment by gianniskapta** [comment]
> > > > Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.
> > > 
> > > 
> > > I've checked it and completed some daily task but it's till showing the red error.
> > 
> > 
> > Because issues on rewards side are still ongoing :)
> > Issue seems to impact Xbox version too so definitely on Microsoft side : https://www.reddit.com/r/MicrosoftRewards/comments/x76mg9/ive_got_issues_with_my_rewards/
> 
> Okay, gonna check it later in the day. It worked fine yesterday but today got bad with the error notification.

Later checked it out and it worked by adding up the complete points but it was still showing the red error notification.

**Comment by 666dsa666** [comment]
> > > > > Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.
> > > > 
> > > > 
> > > > I've checked it and completed some daily task but it's till showing the red error.
> > > 
> > > 
> > > Because issues on rewards side are still ongoing :)
> > > Issue seems to impact Xbox version too so definitely on Microsoft side : https://www.reddit.com/r/MicrosoftRewards/comments/x76mg9/ive_got_issues_with_my_rewards/
> > 
> > 
> > Okay, gonna check it later in the day. It worked fine yesterday but today got bad with the error notification.
> 
> Later checked it out and it worked by adding up the complete points but it was still showing the red error notification.

Issues are still ongoing : https://www.reddit.com/r/MicrosoftRewards/comments/x7bgth/anyone_else_having_problems_with_bing_mobile_mine/

**Comment by Andrew1644563** [comment]
> > > > > > Check on rewards website, issue is not on the extension side but the website is running slow and points are registered either with a delay or not at all and actions have to be repeated.
> > > > > 
> > > > > 
> > > > > I've checked it and completed some daily task but it's till showing the red error.
> > > > 
> > > > 
> > > > Because issues on rewards side are still ongoing :)
> > > > Issue seems to impact Xbox version too so definitely on Microsoft side : https://www.reddit.com/r/MicrosoftRewards/comments/x76mg9/ive_got_issues_with_my_rewards/
> > > 
> > > 
> > > Okay, gonna check it later in the day. It worked fine yesterday but today got bad with the error notification.
> > 
> > 
> > Later checked it out and it worked by adding up the complete points but it was still showing the red error notification.
> 
> Issues are still ongoing : https://www.reddit.com/r/MicrosoftRewards/comments/x7bgth/anyone_else_having_problems_with_bing_mobile_mine/

Everything is back to normal, issues resolved.
