### ISSUE TITLE
Icon changes colour and extension works but can't get past the splash screen

### ISSUE THREAD

**Issue by raynew** [tmxkn1/Microsoft-Reward-Chrome-Ext#85]
![2](https://user-images.githubusercontent.com/37906714/207261178-28ed18a3-424e-4290-86a5-095626eb6ff9.png)
![Screenshot 2022-12-13 081016](https://user-images.githubusercontent.com/37906714/207261182-9c8d6cfb-3b00-430c-ae00-f13fd69480e0.png)

Any ideas? Have tried removing and re-installing the extension, restarting.

**Comment by tmxkn1** [comment]
https://www.bing.com/rewardsapp/flyout?channel=0

Does this link work for you? It should open up a webpage related to Rewards

**Comment by raynew** [comment]
Thanks for responding, yeah that does work. But it was convenient when it was in the extension window. I'll try reinstalling chrome.

**Comment by tmxkn1** [comment]
I have updated the link in the extension. It should work for you now :)
