### ISSUE TITLE
Firefox extension Error, no mobile searches

### ISSUE THREAD

**Issue by FrowningChicken** [tmxkn1/Microsoft-Reward-Chrome-Ext#87]
After the bot goes through the edge searches and regular searches, it does not seem to do any mobile searches successfully. I have tried re-logging in and rebooting the browser. Everything else in the bot is working except for the mobile searches.

**Comment by FrowningChicken** [comment]
I am currently using version 2.24.1.2

**Comment by STX5** [comment]
According to https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/issues/88#issue-1559114666, you have to edit the Microsoft-Reward-Chrome-Ext/src/utility.js file.
 At line 134 , replace the content with these. And reload the extention in your browser.
```
userAgents = {
                'pc': ua.stable.edge_win,
                'mb': 'Mozilla/5.0 (Linux; Android 13; LM-Q710(FGN)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.117 Mobile Safari/537.36',
                'pcSource': 'stable',
                'mbSource': 'stable',
            };
```
This is just a temporary solution, the author might give an update to fix this.

**Comment by tmxkn1** [comment]
Thanks for reporting, mobile UA has been updated.
