### ISSUE TITLE
update on the mobile user agent

### ISSUE THREAD

**Issue by GitzJoey** [tmxkn1/Microsoft-Reward-Chrome-Ext#88]
Hi,

please update to this (at least works on me)
Mozilla/5.0 (Linux; Android 13; LM-Q710(FGN)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.5414.117 Mobile Safari/537.36

**Comment by tmxkn1** [comment]
Thanks, mobile UA has been updated.
