### ISSUE TITLE
Seems to have stopped working

### ISSUE THREAD

**Issue by icase81** [tmxkn1/Microsoft-Reward-Chrome-Ext#92]
Not sure why, but all the functions for the automated search increment seem to have stopped working for me last week. I have two computers with the extension installed and running, but neither increase but also don't show errors. Debug info attached. Thanks!

[DebugInf.txt](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/files/10561990/DebugInf.txt)

**Comment by AntyOof** [comment]
I also have this issue, tried on two computers with different broswers(Chrome and Edge) but they just showing the red error icon. 
[error.txt](https://github.com/tmxkn1/Microsoft-Reward-Chrome-Ext/files/10754707/error.txt)

**Comment by AkiraRiver** [comment]
I can recommend you guys to use ABS, it can do the search and sometimes by doing it with ABS it "repair" the rewards extension and it start to work again.

**Comment by LeFlairGoD** [comment]
Since today the automatic search does not work for me either

![image](https://user-images.githubusercontent.com/64659197/221362306-36fd00b0-9609-4f03-a0f3-e4a58c9b89b6.png)

**Comment by RoyEastmen** [comment]
> -edit- Working again Since today the automatic search does not work for me either
> 
> The error appeared only sporadically and was gone after reloading again ![image](https://user-images.githubusercontent.com/64659197/221362306-36fd00b0-9609-4f03-a0f3-e4a58c9b89b6.png)

How did you get this to work?

**Comment by icase81** [comment]
It randomly started working for me again at some point in the past two weeks. I think MSFT reverted some stuff because everything for the Rewards had a new look to it and now it's back to the old look.

**Comment by tmxkn1** [comment]
Sorry I've lost track of issues, but hopefully, this one has been resolved following the new update?

**Comment by RoyEastmen** [comment]
Yes, thank you. The extension now works perfectly.
