### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by TylerNader** [tmxkn1/Microsoft-Reward-Chrome-Ext#94]
It gives me an err and when i go to the extension page theres errors too.

**Comment by AkiraRiver** [comment]
Hi, try to disconnect and reconnect again, and when the extension is in red try to click it a few times if it doesn't work try to close and open again your browser, that should resolve the problem

**Comment by tmxkn1** [comment]
I guess this is the issue with UA which should be fixed now. Sorry for the delay in reply.
