### ISSUE TITLE
it starts mobile searches very late and also it gives error icon many a times while searching 

### ISSUE THREAD

**Issue by Lakhanpratap24** [tmxkn1/Microsoft-Reward-Chrome-Ext#95]
Many a times this extension gives red error symbol and also stops while performing searches 
kindly help me out for this error
Also

There is an issue of manifest version also which states as "Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

**Comment by Gustiviy** [comment]
Same here, for me the icon is blue but changes to red with the error being "Cannot find working UAs for pc and mobile."

**Comment by tmxkn1** [comment]
The issue should be fixed now. Sorry for the delay in reply.
